include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../modules/secrets"
}

dependency "network" {
  config_path = "../network"

  mock_outputs = {
    vpc_id = "vpc-00000000000000000"
  }
}

inputs = {
  project_name = "responsible-ai"
  environment  = "dev"
  vpc_id       = dependency.network.outputs.vpc_id

  # Secrets to store
  secrets = {
    # Provider credential. Mounted only into the LiteLLM proxy task.
    groq_api_key = {
      description = "Groq API key used by the LiteLLM proxy"
    }

    # LiteLLM admin key (operators only; generated by Terraform).
    litellm_master_key = {
      description = "LiteLLM proxy master key"
    }

    # LiteLLM virtual key issued to the AI Gateway via /key/generate after the
    # proxy is up. Placeholder until an operator stores the generated key.
    litellm_gateway_key = {
      description = "LiteLLM virtual key for the AI Gateway service"
    }

    database_master_password = {
      description = "Aurora PostgreSQL master password"
    }

    jwt_secret = {
      description = "JWT signing secret for Cognito"
    }
  }

  tags = {
    Module = "secrets"
  }
}
